# Generated by Django 4.2.5 on 2023-09-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('position', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('date_of_employment', models.DateField()),
                ('date_of_dismissal', models.DateField()),
            ],
        ),
    ]
